### ISSUE TITLE
fuse-nfs.c:39:21: error: storage size of ‘nfs_st’ isn’t known

### ISSUE THREAD

**Issue by chalianwar** [sahlberg/fuse-nfs#1]
Compilation issue:

Making all in doc
make[1]: Entering directory `/home/ali/git/fuse-nfs/doc'
test -z "/usr/bin/xsltproc" || /usr/bin/xsltproc -o fuse-nfs.1 http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl fuse-nfs.xml
/bin/bash: /usr/bin/xsltproc: No such file or directory
make[1]: [fuse-nfs.1] Error 127 (ignored)
make[1]: Leaving directory`/home/ali/git/fuse-nfs/doc'
Making all in fuse
make[1]: Entering directory `/home/ali/git/fuse-nfs/fuse'
gcc -DPACKAGE_NAME=\"fuse-nfs\" -DPACKAGE_TARNAME=\"fuse-nfs\" -DPACKAGE_VERSION=\"1.0.0\" -DPACKAGE_STRING=\"fuse-nfs\ 1.0.0\" -DPACKAGE_BUGREPORT=\"ronniesahlberg@gmail.com\" -DPACKAGE_URL=\"\" -DPACKAGE=\"fuse-nfs\" -DVERSION=\"1.0.0\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -I.     -g -O2 -D_FILE_OFFSET_BITS=64 -MT fuse-nfs.o -MD -MP -MF .deps/fuse-nfs.Tpo -c -o fuse-nfs.o fuse-nfs.c
fuse-nfs.c: In function ‘fuse_nfs_getattr’:
fuse-nfs.c:39:21: error: storage size of ‘nfs_st’ isn’t known
  struct nfs_stat_64 nfs_st;
                     ^
make[1]: *** [fuse-nfs.o] Error 1
make[1]: Leaving directory`/home/ali/git/fuse-nfs/fuse'
make: **\* [all-recursive] Error 1

**Comment by chalianwar** [comment]
Interestingly the libnfs.h does not contain this struct. Let me find out the reason.

**Comment by chalianwar** [comment]
I used "apt-get install libnfs-dev" to install the lib.

**Comment by chalianwar** [comment]
As a workaround I manually installed the libnfs-1.10.0.tar.gz.

**Comment by estadtherr** [comment]
I noticed this as well, that Ubuntu 14.04.x has an older version of libnfs (1.3.0). I couldn't find a way to tell the fuse-nfs `configure` script where libnfs was located. Is there an elegant way to do that, or did you just play with CPPFLAGS/LDFLAGS to get it to build?

**Comment by sahlberg** [comment]
You should be able to build manually and statically link with a different
libnfs version.


Something like this should work :
cd fuse
gcc -o fuse-nfs  -I<path-to-where-you-built-libnfs>/include   fuse-nfs.c
<path-to-where-you-built-libnfs>/lib/.libs/libnfs.a -lfuse

**Comment by paulcwarren** [comment]
For us, we were able to get this building on ubuntu 14.04 (after building the downloaded tarball for libnfs) by changing `fuse/Makefile.am` to look like this:
```
bin_PROGRAMS = fuse-nfs

AM_CFLAGS = -I../../libnfs/include
AM_LDFLAGS = ../../libnfs/lib/.libs/libnfs.a -lfuse
```

**Comment by sahlberg** [comment]
The problem is that ubuntu ships very old versions of libnfs which lacks
the stat structure and other part of the API.
(which was added several years ago:-( )

You don't need to modify the makefile, though that does work.

An alternative is to
1, remove the version of libnfs that ubuntu shipped
2, build and install an uptodate version of libnfs from sources.
    configure --prefix=/usr
    make
   make install

then you dont need to modify the makefile.
