### ISSUE TITLE
uid gets incorrectly assigned gid value in update_rpc_credentials()

### ISSUE THREAD

**Issue by julian-hj** [sahlberg/fuse-nfs#10]
see
https://github.com/sahlberg/fuse-nfs/blob/master/fuse/fuse-nfs.c#L80

the end result is that if we mount with something like this
```
fuse-nfs -n "nfs://10.10.200.72/export2/certs?uid=3000&gid=3050" -m /tmp/certsdir
```
and then we go touch a file in that directory, it ends up on the server owned by user 3050:3050

**Comment by nabbar** [comment]
Arf... 
Thanks for your help,
We fix it today

**Comment by julian-hj** [comment]
This is passing again in our CI pipeline--thanks for the quick fix!

**Comment by nabbar** [comment]
Great news :)
