### ISSUE TITLE
Cygwin should not use Winsock2

### ISSUE THREAD

**Issue by billziss-gh** [sahlberg/fuse-nfs#18]
As a follow up to sahlberg/libnfs@e35a44e2bf3380ec4bd81c5232e4a8234bfa450c the same problem exists on fuse-nfs: it appears that the winsock2 library is erroneously included by the `configure.ac` script.

From https://github.com/sahlberg/fuse-nfs/blob/master/configure.ac#L54-L59:
```
OLD_LIBS=$LIBS
LIBS+=" -lws2"
AC_LINK_IFELSE([AC_LANG_PROGRAM([[#include <winsock2.h>]], [[gethostbyname ("");]])], [], [LIBS=$OLD_LIBS])
OLD_LIBS=$LIBS
LIBS+=" -lws2_32"
AC_LINK_IFELSE([AC_LANG_PROGRAM([[#include <winsock2.h>]], [[gethostbyname ("");]])], [], [LIBS=$OLD_LIBS])
```

I am not well versed in autoconf, but looking at `config.log` this checks if this minimal program compiles:

```
#include <winsock2.h>
int main()
{
    gethostbyname ("");
    return 0;
}
```

Unfortunately this program does compile on Cygwin (at least on my machine), which results in Cygwin picking up the `-lws2_32` option, which is erroneous as discussed in sahlberg/libnfs@e35a44e2bf3380ec4bd81c5232e4a8234bfa450c.

I have a crude patch that just comments out this section, but perhaps a better solution would be to not do this test at all on Cygwin. Unfortunately my knowledge of autoconf is not enough to competently produce a patch here, but I am happy to test if someone else does.

---

**UPDATE**

My gcc compiler reports the following as include directories:

```
$ gcc -E -Wp,-v - </dev/null
ignoring nonexistent directory "/usr/local/include"
ignoring nonexistent directory "/usr/lib/gcc/x86_64-pc-cygwin/5.4.0/include-fixed"
ignoring nonexistent directory "/usr/lib/gcc/x86_64-pc-cygwin/5.4.0/../../../../x86_64-pc-cygwin/include"
ignoring duplicate directory "/usr/lib/gcc/x86_64-pc-cygwin/5.4.0/../../../../x86_64-pc-cygwin/lib/../lib/../../include/w32api"
#include "..." search starts here:
#include <...> search starts here:
 /usr/lib/gcc/x86_64-pc-cygwin/5.4.0/include
 /usr/include
 /usr/lib/gcc/x86_64-pc-cygwin/5.4.0/../../../../lib/../include/w32api
End of search list.
# 1 "<stdin>"
# 1 "<built-in>"
# 1 "<command-line>"
# 1 "<stdin>"
```

The `/usr/lib/gcc/x86_64-pc-cygwin/5.4.0/../../../../lib/../include/w32api` is really `/usr/include/w32api`, which contains the Win32 headers (including `winsock2.h`).

I am under the impression that the `/usr/include/w32api` directory should not be included in the default header searches, so this may be a change with recent Cygwin.

**Comment by Daniel-Abrecht** [comment]
While winsock2 isn't required with cygwin, it is required when mingw is used. I'll try to change this check a bit so it works in either case.

**Comment by billziss-gh** [comment]
Thank you. PR #19 appears to have fixed this.
