### ISSUE TITLE
NFSv4 issue

### ISSUE THREAD

**Issue by hmlingesh** [sahlberg/fuse-nfs#23]
Hello Team,

Using this lib, we are trying to mount NFSv4 protocol based server directory into local. But getting below exception.
Failed to mount nfs share : nfs_service failed ERR libnfs error: rpc_service: socket error Connection timed out(110).
 
please could you confirm is this issue is related to protocol version or something else.

/home/app/bin/fuse-nfs -n "nfs://x.x.x.x/workspace/workspace?uid=10110&gid=10111&version=4" -m /home/app/nfs

Regards
Lingesh M

**Comment by sahlberg** [comment]
Neither libnfs nor fuse-nfs supports NFSv4. So this is an expected failure.

Libnfs support for NFSv4 is a work in progress and may become available towards the end of the year.
After that, fuse-nfs should work with some luck.
