### ISSUE TITLE
Android: stat struct [patch]?

### ISSUE THREAD

**Issue by nocturnalowl** [sahlberg/fuse-nfs#3]
In fuse/fuse-nfs.c: function fuse_nfs_getattr
You use st_atim, but this member structure isn't defined in the android header files.

I've changed st_atim.tv_sec to st_atime and st_atim.tv_nsec to st_atime_nsec. It compiled and tested it on my device and worked (could mount nfs on my phone). I know not only there need to be tests but it must compile on all the platforms you support. So I don't know if this "solution" doesn't break on your main platforms.

In any case, this works(?) when using the cross compiler for android:

--
```
diff --git a/fuse/fuse-nfs.c b/fuse/fuse-nfs.c
index fb5457b..29e0db6 100644
--- a/fuse/fuse-nfs.c
+++ b/fuse/fuse-nfs.c
@@ -50,12 +50,12 @@ static int fuse_nfs_getattr(const char *path, struct stat *stbuf)
        stbuf->st_size         = nfs_st.nfs_size;
        stbuf->st_blksize      = nfs_st.nfs_blksize;
        stbuf->st_blocks       = nfs_st.nfs_blocks;
-       stbuf->st_atim.tv_sec  = nfs_st.nfs_atime;
-       stbuf->st_atim.tv_nsec = nfs_st.nfs_atime_nsec;
-       stbuf->st_mtim.tv_sec  = nfs_st.nfs_mtime;
-       stbuf->st_mtim.tv_nsec = nfs_st.nfs_mtime_nsec;
-       stbuf->st_ctim.tv_sec  = nfs_st.nfs_ctime;
-       stbuf->st_ctim.tv_nsec = nfs_st.nfs_ctime_nsec;
+       stbuf->st_atime        = nfs_st.nfs_atime;
+       stbuf->st_atime_nsec   = nfs_st.nfs_atime_nsec;
+       stbuf->st_mtime        = nfs_st.nfs_mtime;
+       stbuf->st_mtime_nsec   = nfs_st.nfs_mtime_nsec;
+       stbuf->st_ctime        = nfs_st.nfs_ctime;
+       stbuf->st_ctime_nsec   = nfs_st.nfs_ctime_nsec;
 
        return ret;
 }
```

**Comment by sahlberg** [comment]
Thanks.

I have checked in a configure test for linux 2.6+ stat structure and
fallback to st_atime[_nsec] if not present.
Please try.

**Comment by nocturnalowl** [comment]
Works. You can close this issue.

Thanks
