### ISSUE TITLE
Failing to compile

### ISSUE THREAD

**Issue by mmhamed** [sahlberg/fuse-nfs#41]
I'm trying to compile/install the project on a setup which has  no connection to the internet. (I succeeded with downloading the project and the relevant libraries with different methods). But when I reach the "make", I get some errors like:

make[2]: Entering directory '/home/ubuntu/fuse-nfs/doc'
test -z "/usr/bin/xsltproc" || /usr/bin/xsltproc -o fuse-nfs.1 http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl fuse-nfs.xml
error : Resource temporarily unavailable
warning: failed to load external entity "http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl"
cannot parse http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl

Is it not possible to compile without internet connection ? (I get that it seems there's no point in installing it without internet, but I'm trying something else).

Thanks

**Comment by sahlberg** [comment]
It fails building the documentation.

Remove 'doc' from the SUBDIRS assignment in Makefile.am,
reconfigure the project, and try compiling it again.

**Comment by mmhamed** [comment]
It worked, thanks a lot :)
I would be happy if you can elaborate on what this "documentation" is, because I don't want to remove an important feature by mistake.

Thanks
